config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

  resources :blocks, only: [:index, :create, :destroy]
  resources :tweets, only: [:index, :create, :destroy]
  resources :words, only: [:index, :new, :create, :destroy]

end

app/models/block.rb
class Block < ActiveRecord::Base
  belongs_to :user
  has_one :tweet

  validates :screen_name, presence: true
  validates :name, presence: true
  validates :created_at, presence: true
  validates :twitter_id, presence: true

  def self.create_block(blocked_user, current_user) 
    Block.where(screen_name: blocked_user.screen_name, user_id: current_user.id).first_or_create do |block|
        block.name = blocked_user.name
        block.screen_name = blocked_user.screen_name
        block.created_at = blocked_user.created_at
        block.twitter_id = blocked_user.id.to_s
        block.user_id = current_user.id
    end
  end

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user

  validates :screenname, presence: true
  validates :name, presence: true
  validates :text, presence: true
  validates :date, presence: true
  validates :tweetid, presence: true, uniqueness: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :blocks
  has_many :words
  has_many :tweets

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.twitter_screen_name = auth["info"]["nickname"]
      user.twitter_display_name = auth["info"]["name"]
    end
  end

  # Gathering all trigger words
  def get_my_words
    # Words associated with online harassment
    trigger_words = ["rape","murder","nigger","slut","whore","bitch","cunt","kill","die","testword"]
    my_words = Word.where(user_id: self.id)
    my_words.each do |word|
      trigger_words << word.word
    end
    return trigger_words
  end

  # Compare text of a mention to trigger words array. Returns a username if user's tweet text includes a trigger word.
  def determine_blocks(twitter, mentions)
    
    words_to_check = get_my_words
    users_to_block = []

    mentions.each do |mention|
      mention.text.split(" ").each do |word|
        if words_to_check.include?(word) && twitter.friendship?(self, mention.user.screen_name) == false
            users_to_block << mention.user.screen_name
        end
      end
    end
    return users_to_block
  end


  # Compares text of a mention to trigger words array. Returns a new tweet object for any tweet containing a trigger word.
  def determine_triggers(twitter, mentions)
    
    words_to_check = get_my_words
    trigger_tweets = []

    mentions.each do |mention|
      mention.text.split(" ").each do |word|
        if words_to_check.include?(word) && twitter.friendship?(self, mention.user.screen_name) == false
            trigger_tweets << mention
        end
      end
    end
    return trigger_tweets
  end

end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :user

  validates :word, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    else
      redirect_to '/'
    end 
  end

    def initialize_twitter
    @twitter = Twitter::REST::Client.new do |config|
      config.consumer_key = ENV["twitter_key"]
      config.consumer_secret = ENV["twitter_secret"]
      config.access_token = session[:token]
      config.access_token_secret = session[:token_secret]
    end
  end

end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController

  before_action :current_user, :initialize_twitter

  def index
    # Checking for abusive tweets, and identifying the users who sent them
    @new_mentions = @twitter.mentions_timeline
    @users_to_block = @current_user.determine_blocks(@twitter, @new_mentions)

    # Blocking all users identified in previous step
    @users_to_block.each do |user|
      @twitter.block(user)
    end

    # Ensuring all users blocked on Twitter are also persisted to DB
    @all_blocks = @twitter.blocked
    @all_blocks.each do |blocked_user|
      Block.create_block(blocked_user, @current_user)
    end

    # Collecting blocked users & mentions for current user to display in views
    @blocks = Block.where(user_id: @current_user.id)
    @mentions = @twitter.mentions_timeline
    # byebug
  end

  def create

  end

  def destroy
    @block = Block.find(params[:id])
    @twitter.unblock(@block.screen_name)
    @block.destroy   
    # render '/blocks'
    respond_to do |format|
      format.json { render json: @block, status: 200 }
    end
  end

  private

  def block_params
    params.require(:block).permit(:screen_name, :name, :created_at, :twitter_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create     
    auth = request.env["omniauth.auth"]     
    @user = User.find_by_uid(auth["uid"]) || User.create_with_omniauth(auth)
    # byebug  
    session[:user_id] = @user.id     
    session[:token] = auth["credentials"]["token"]
    session[:token_secret] = auth["credentials"]["secret"]
    session[:twitter_screen_name] = @user.twitter_screen_name
    redirect_to '/blocks', :notice => "signed in as @"+ @user.twitter_screen_name
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "signed out!"
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :current_user, :initialize_twitter

  def index
    @trigger_tweets = @current_user.determine_triggers(@twitter, @twitter.mentions_timeline)
    @trigger_tweets.each do |tweet|
      Tweet.create(screenname: tweet.user.screen_name, name: tweet.user.name, text: tweet.text, date: tweet.created_at, tweetid: tweet.id.to_s, user_id: @current_user.id)
    end
    @tweets = Tweet.where(user: @current_user)
  end

  def create
    @tweet = Tweet.new(tweet_params)
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy   
    respond_to do |format|
      format.json { render json: @tweet, status: 200 }
    end
  end

  private

  def tweet_params
      params.permit(:screenname, :name, :text, :date, :tweetid)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    session
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  before_action :current_user, :initialize_twitter

  def index
    @words = Word.where(user: @current_user)
    @word = Word.new
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.new(word_params)
    @word.user_id = @current_user.id
    if @word.save
      redirect_to '/words'
    end
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy
    redirect_to words_path
  end

  private

  def word_params
      params.require(:word).permit(:word)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blocks/index.html.erb
<%= render 'layouts/nav' %>

<div class="blocks">

  <h2>your blocks</h2>

    <ul class="block-list">  
      <% if @blocks != [] %> 
        <% @blocks.each do |block| %>
          <li class="unblock" id="<%= block.id %>" >@<%= block.screen_name %>, <%= block.name %><br>
            <button class="unblock-button">unblock</button></li>
        <% end %>
      <% else %>
        <li>You have no blocked users.</li>
      <% end %>
    </ul>

  <h2>recent mentions</h2>
  <ul class="block-list">
    <% @mentions.each do |mention| %>
      <li>@<%= mention.user.screen_name %>: <%= mention.text %></li>
    <% end %>
  </ul>

</div>

<div class="menu">
  <ul>
    <li><%= link_to "view saved trigger tweets", tweets_path %></li>
    <li><%= link_to "set a new trigger word", words_path %></li>
  </ul>
</div>

app/views/layouts/_nav.html.erb
<nav><span class="notice"><%= notice %></span> <span class="blockparty"><%= link_to 'block party', blocks_path %> | <%= link_to 'sign out', signout_path %></span></nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlockParty</title>
  <link href='https://fonts.googleapis.com/css?family=Quicksand:300,400' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= yield %>

</body>
</html>

app/views/tweets/index.html.erb
<%= render 'layouts/nav' %>

<div class="blocks">

  <h2>your trigger tweets</h2>
  <p class="subheader">Each of these tweets triggered a block due to abusive language.</p>

    <ul class="block-list">  
      <% if @tweets != [] %> 
        <% @tweets.each do |tweet| %>
          <li class="delete-tweet" id="<%= tweet.id %>" >@<%= tweet.screenname %>, <%= tweet.name %><br>
            <%= tweet.text %><br>
            <a href="https://twitter.com/<%= tweet.screenname %>/status/<%= tweet.tweetid %>"><%= tweet.date %></a><br>
            <button class="tweet-button">delete tweet</button></li>
        <% end %>
      <% else %>
        <li>You have no saved trigger tweets.</li>
      <% end %>
    </ul>

</div>

app/views/welcome/index.html.erb
<div class="welcome">
    <div class="intro">
      <h1>block party</h1>
      <p>Let's make Twitter fun again!</p> 
      <p>We auto-block the jerks so you can focus on the important stuff.</p>
      <button id="about">tell me more</button>
    </div>
    <div class="about">
      <p>Everyone deserves to participate in online discourse, but many voices are silenced by abusive tweets from online harassers, which often threaten physical violence and sexual assault.</p>

      <p>Block Party hopes to alleviate this problem by blocking abusive users on your behalf. If you receive a tweet containing abusive language, we automatically block the offending user and remove the tweet from your timeline. We'll save a record of the trigger tweet in case you need it as evidence, and it'll be available here even if it was deleted from Twitter.</p>

      <p>Block Party will never block a Twitter user that you follow, and we will never post a Tweet on your behalf.</p>

      <p>If you aren't familiar with the problem of online harassment, on Twitter and other online spaces, this <a href="http://www.psmag.com/navigation/health-and-behavior/women-arent-welcome-internet-72170/">Pacific Standard article by Amanda Hess</a> is an excellent introduction to the issue.</p>
      <button id="hide">hide</button>
    </div>
</div>

<div class="signin">
  <a href="https://block-party-wdi.herokuapp.com/auth/twitter"><button id="signin">sign in with Twitter</button></a>
</div>

app/views/words/index.html.erb
<%= render 'layouts/nav' %>

<div class="blocks">

  <h2>your trigger words</h2>
  <p class="subheader">Save additional words that you would like to trigger a block.</p>

    <ul class="block-list">  
      <% if @words != [] %> 
        <% @words.each do |word| %>
          <li class="delete-word" id="<%= word.id %>" ><%= word.word %><br>
            <button class="word-button">delete word</button></li>
        <% end %>
      <% else %>
        <li>You have no additional trigger words saved.</li>
      <% end %>
    </ul>

  <h3>create an additional trigger word</h3>

  <%= form_for(@word) do |f| %>
    <% if @word.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

        <ul>
        <% @word.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.label :word %><br>
    <%= f.text_field :word %>  
    <%= f.submit %>
  <% end %>

</div>